CREATE TABLE `judges`(
`id` INT(11) NOT NULL AUTO_INCREMENT,
`name` VARCHAR(255) NULL,
`email` VARCHAR(255) NULL,
`phone` VARCHAR(255) NULL,
`url` VARCHAR(255) NULL,
`schedule_MON_TH` VARCHAR(255) NULL,
`schedule_FR` VARCHAR(255) NULL,
`schedule_BREAK` VARCHAR(255) NULL,
`adress` VARCHAR(255) NULL,
PRIMARY KEY (`id`));